name: detector_de_madera
description: A new Flutter project.

publish_to: 'none'
version: 1.0.2+12

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  flutter_spinkit: ^5.2.0
  flutter_launcher_icons: ^0.13.1
  dio: ^5.3.3
  animated_text_kit: ^4.2.2
  awesome_dialog: ^3.1.0
  another_flutter_splash_screen: ^1.2.1
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  hive_flutter: ^1.1.0
  purchases_flutter: ^6.30.1
  modal_progress_hud_nsn: ^0.5.1
  uuid: ^4.4.2
  url_launcher: ^6.3.0
  go_router: ^14.2.1
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  provider: ^6.1.2
  font_awesome_flutter: ^10.7.0
  sensors_plus: ^4.0.2
  audioplayers: ^5.2.1
  noise_meter: ^5.0.2
  permission_handler: ^11.3.1
  fl_chart: ^0.69.2
  neumorphic_ui: ^1.0.1
  intl: ^0.19.0
  webview_flutter: ^4.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/metal_detection.mp3